[package]
name = "chip-8"
version = "0.1.0"
authors = ["Hugo Tunius <h@tunius.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
minifb = "0.13"
clap = "2"
